/* CVS $Id: $ */
package ac.at.tuwien.logparser.entities.schema;

import com.hp.hpl.jena.ontology.*;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/Agnes/Documents/TU/Diplomarbeit/sba-file-system-log-service/src/main/resources/vocabs/file_access_events.rdfs
 *
 * @author Auto-generated by schemagen on 17 Nov 2018 10:53
 */
public class File_access_events {
    /**
     * <p>The ontology model that holds the vocabulary terms</p>
     */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://purl.org/sepses/vocab/event/fileAccess#";

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);

    public static final DatatypeProperty id = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#id");

    public static final DatatypeProperty eventID = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#eventID");

    public static final ObjectProperty relatedTo = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#relatedTo");

    public static final ObjectProperty hasAction = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasAction");

    public static final ObjectProperty hasProgram = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasProgram");

    public static final ObjectProperty hasSourceFile = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasSourceFile");

    public static final ObjectProperty hasSourceHost = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasSourceHost");

    public static final ObjectProperty hasTargetFile = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasTargetFile");

    public static final ObjectProperty hasTargetHost = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasTargetHost");

    public static final ObjectProperty hasUser = M_MODEL.createObjectProperty("http://purl.org/sepses/vocab/event/fileAccess#hasUser");

    public static final DatatypeProperty actionName = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#actionName");

    public static final DatatypeProperty fileName = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#fileName");

    public static final DatatypeProperty pathName = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#pathName");

    public static final DatatypeProperty md5CheckSum = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#md5CheckSum");

    public static final DatatypeProperty hostName = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#hostName");

    public static final DatatypeProperty ip4Address = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#ip4Address");

    public static final DatatypeProperty ip6Address = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#ip6Address");

    public static final DatatypeProperty ipAddress = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#ipAddress");

    public static final DatatypeProperty programName = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#programName");

    public static final DatatypeProperty pid = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#pid");

    public static final DatatypeProperty timestamp = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#timestamp");

    public static final DatatypeProperty userName = M_MODEL.createDatatypeProperty("http://purl.org/sepses/vocab/event/fileAccess#userName");

    public static final OntClass Action = M_MODEL.createClass("http://purl.org/sepses/vocab/event/fileAccess#Action");

    public static final OntClass File = M_MODEL.createClass("http://purl.org/sepses/vocab/event/fileAccess#File");

    public static final OntClass FileAccessEvent = M_MODEL.createClass("http://purl.org/sepses/vocab/event/fileAccess#FileAccessEvent");

    public static final OntClass Host = M_MODEL.createClass("http://purl.org/sepses/vocab/event/fileAccess#Host");

    public static final OntClass Program = M_MODEL.createClass("http://purl.org/sepses/vocab/event/fileAccess#Program");

    public static final OntClass User = M_MODEL.createClass("http://purl.org/sepses/vocab/event/fileAccess#User");

}
