/* CVS $Id: $ */
package ac.at.tuwien.logparser.entities.schema;

import com.hp.hpl.jena.ontology.*;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
/*import org.apache.jena.ontology.*;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Resource;
*/
/**
 * Vocabulary definitions from file:/Users/Agnes/Documents/TU/Diplomarbeit/sba-file-system-log-service/src/main/resources/vocabs/file-system-log-schema.rdfs 
 * @author Auto-generated by schemagen on 14 Sep 2018 12:12 
 */
public class File_system_log_schema {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final ObjectProperty hasFile = M_MODEL.createObjectProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#hasFile" );
    
    public static final ObjectProperty hasLogType = M_MODEL.createObjectProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#hasLogType" );
    
    public static final ObjectProperty hasProcess = M_MODEL.createObjectProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#hasProcess" );
    
    public static final ObjectProperty hasUser = M_MODEL.createObjectProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#hasUser" );
    
    public static final ObjectProperty originatesFrom = M_MODEL.createObjectProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#originatesFrom" );
    
    public static final DatatypeProperty id = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#id" );

    public static final DatatypeProperty accessCall = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#accessCall" );

    public static final DatatypeProperty accessInfo = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#accessInfo" );
    
    public static final DatatypeProperty domain = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#domain" );
    
    public static final DatatypeProperty eventID = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#eventID" );
    
    public static final DatatypeProperty filetype = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#filetype" );
    
    public static final DatatypeProperty hostName = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#hostName" );
    
    public static final DatatypeProperty instanceId = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#instanceId" );
    
    public static final DatatypeProperty ip4Address = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#ip4Address" );
    
    public static final DatatypeProperty ip6Address = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#ip6Address" );
    
    public static final DatatypeProperty ipAddress = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#ipAddress" );
    
    public static final DatatypeProperty logFilePath = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#logFilePath" );
    
    public static final DatatypeProperty logMessage = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#logMessage" );
    
    public static final DatatypeProperty logTypeName = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#logTypeName" );
    
    public static final DatatypeProperty pathname = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#pathname" );
    
    public static final DatatypeProperty processID = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#processID" );
    
    public static final DatatypeProperty processname = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#processname" );
    
    public static final DatatypeProperty timestamp = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#timestamp" );
    
    public static final DatatypeProperty username = M_MODEL.createDatatypeProperty( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#username" );
    
    public static final OntClass File = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#File" );
    
    public static final OntClass FileSystemLogEntry = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#FileSystemLogEntry" );
    
    public static final OntClass Host = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#Host" );
    
    public static final OntClass LogEntry = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#LogEntry" );
    
    public static final OntClass LogType = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#LogType" );
    
    public static final OntClass Process = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#Process" );
    
    public static final OntClass USBDeviceLogEntry = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#USBDeviceLogEntry" );
    
    public static final OntClass UnixFileSystemLogEntry = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#UnixFileSystemLogEntry" );
    
    public static final OntClass User = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#User" );
    
    public static final OntClass WinFileSystemLogEntry = M_MODEL.createClass( "http://sepses.ifs.tuwien.ac.at/vocab/fileSystemLog#WinFileSystemLogEntry" );
    
}
