/* CVS $Id: $ */
package ac.at.tuwien.logparser.entities.schema;

import com.hp.hpl.jena.ontology.*;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/Agnes/Documents/TU/Diplomarbeit/sba-file-system-log-service/src/main/resources/vocabs/process-info.rdfs
 *
 * @author Auto-generated by schemagen on 30 Nov 2018 11:36
 */
public class History_schema {
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);


    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://sepses.ifs.tuwien.ac.at/vocab/history#";

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);

    public static final OntClass History = M_MODEL.createClass("http://sepses.ifs.tuwien.ac.at/vocab/history#History");

    public static final DatatypeProperty id = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#id");

    public static final DatatypeProperty name = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#name");

    public static final DatatypeProperty timestamp = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#timestamp");

    public static final DatatypeProperty sourceFileName = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#sourceFileName");

    public static final DatatypeProperty targetFileName = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#targetFileName");

    public static final ObjectProperty next = M_MODEL.createObjectProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#next");

    public static final DatatypeProperty duplicate = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#duplicate");

    public static final DatatypeProperty move = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#move");

    public static final DatatypeProperty rename = M_MODEL.createDatatypeProperty("http://sepses.ifs.tuwien.ac.at/vocab/history#rename");
}
